### ISSUE TITLE
'Trauma Center - Under the Knife' 1 and 2 are missing their box art

### ISSUE THREAD

**Issue by leorubino** [libretro-thumbnails/Nintendo_-_Nintendo_DS#140]
Hello, this is my first time contributing on GitHub, so apologies if this is not a valid issue request. Both of the 'Trauma Center - Under the Knife' games are missing artwork.I have attached high-quality versions for both covers:

[Trauma Center: Under the Knife](https://i.imgur.com/VldFRgE.jpg)
[Trauma Center: Under the Knife 2](https://i.imgur.com/ZgTCgAT.jpg)

**Comment by RobLoach** [comment]
Thanks! Glad you're looking to contribute some boxart. If you're looking to push up quicker, you can....
1. Resize to 512px wide
2. Save as .png
3. Upload the files directly as a Pull Request. You can Drag and drop them into the folder through the GitHub UI, or the desktop app :smile:
