### ISSUE TITLE
Add new entry for Pokemon - SoulSilver Version (USA, Australia)

### ISSUE THREAD

**Issue by masanasake** [libretro-thumbnails/Nintendo_-_Nintendo_DS#198]
![Pokemon - SoulSilver Version (USA)](https://user-images.githubusercontent.com/105944840/169704151-35ee2980-782b-474c-9292-c6ebf793e255.png)

**Comment by MarcoEstevez** [comment]
Please [masanasake](https://github.com/masanasake) test again
