### ISSUE TITLE
Add new entry for New Super Mario Bros. (USA, Australia)

### ISSUE THREAD

**Issue by masanasake** [libretro-thumbnails/Nintendo_-_Nintendo_DS#199]
![New Super Mario Bros  (USA)](https://user-images.githubusercontent.com/105944840/169704285-56170f9f-2bb4-4c54-88cc-f93e4b39027d.png)

**Comment by MarcoEstevez** [comment]
Please [masanasake](https://github.com/masanasake) test again!
