### ISSUE TITLE
Add entry for Super Mario 64 DS (USA, Australia) (Rev 1)

### ISSUE THREAD

**Issue by masanasake** [libretro-thumbnails/Nintendo_-_Nintendo_DS#200]
![Super Mario 64 DS (USA) (Rev 1)](https://user-images.githubusercontent.com/105944840/169704349-3b50ec73-f97a-4171-b3a2-be766db1d0a1.png)

**Comment by MarcoEstevez** [comment]
Please [masanasake](https://github.com/masanasake) test again
