### ISSUE TITLE
Add entry for Nintendogs - Lab & Friends (USA, Australia)

### ISSUE THREAD

**Issue by masanasake** [libretro-thumbnails/Nintendo_-_Nintendo_DS#201]
![Nintendogs - Lab _ Friends (USA)](https://user-images.githubusercontent.com/105944840/169704389-93c8742b-b9e7-4780-99f3-933b860c10c1.png)

**Comment by MarcoEstevez** [comment]
[masanasake](https://github.com/masanasake) please re-test

**Comment by masanasake** [comment]
The main thread on Star fox Command mentions that this isn't being pulled from the "download thumbnails" option when you select the game, but can be downloaded from desktop menu. But I do have another issue with this one: I'm an idiot and used a PAL box for this. Could you please change it out for this USA one? Sorry for the hassle.
![Nintendogs - Lab _ Friends (USA)](https://user-images.githubusercontent.com/105944840/169822559-b66ea734-cd0a-4c49-8158-5f1805b998ac.png)

**Comment by MarcoEstevez** [comment]
I'll fix it
