### ISSUE TITLE
New entry - Nintendogs - Lab & Friends (USA)

### ISSUE THREAD

**Issue by masanasake** [libretro-thumbnails/Nintendo_-_Nintendo_DS#205]
Could you add another entry for "Nintendogs - Lab & Friends (USA)"? I didn't realize it but the cover art for the other one is PAL. Please use this new one, possibly for both if you wouldn't mind.
![Nintendogs - Lab _ Friends (USA)](https://user-images.githubusercontent.com/105944840/169822057-8030a8d0-f434-48cd-80b5-e9a333b3cdd9.png)

**Comment by MarcoEstevez** [comment]
Should be correct now

**Comment by masanasake** [comment]
Thank you for updating it. So the USA/Australia entry added to the master branch works for the desktop menu method, however it does not pull it via the per game downloader. I've noticed when navigating github, it defaults to branch eef226231 when trying to access any of the specific libraries. Does something need to happen with this? I'm not sure what's going on, but it looks like that per game "Download thumbnails" option is pulling them from that eef branch, and not the master branch? Can you make sense of it? The Steam version of retroarch does not have the online updater/desktop, so it seems worthwhile to sort this out
