### ISSUE TITLE
missing shots for rev 1 and rev 2 of "DS Kageyama Method Dennou Hanpuku - Tadashii Kanji Kakitori-kun - Kondo wa Kanken Taisaku Da yo! (Japan)"

### ISSUE THREAD

**Issue by cloph** [libretro-thumbnails/Nintendo_-_Nintendo_DS#224]
https://github.com/RobLoach/libretro-thumbnails-check/blob/9fd42ff920365b6c4ae71425daa44969273d4c79/out/Nintendo%20-%20Nintendo%20DS.txt#L1442

There's https://thumbnails.libretro.com/Nintendo%20-%20Nintendo%20DS/Named_Boxarts/DS%20Kageyama%20Method%20Dennou%20Hanpuku%20-%20Tadashii%20Kanji%20Kakitori-kun%20-%20Kondo%20wa%20Kanken%20Taisaku%20Da%20yo%21%20%28Japan%29.png

but no https://thumbnails.libretro.com/Nintendo%20-%20Nintendo%20DS/Named_Boxarts/DS%20Kageyama%20Method%20Dennou%20Hanpuku%20-%20Tadashii%20Kanji%20Kakitori-kun%20-%20Kondo%20wa%20Kanken%20Taisaku%20Da%20yo%21%20%28Japan%29%20%28Rev%201%29.png or https://thumbnails.libretro.com/Nintendo%20-%20Nintendo%20DS/Named_Boxarts/DS%20Kageyama%20Method%20Dennou%20Hanpuku%20-%20Tadashii%20Kanji%20Kakitori-kun%20-%20Kondo%20wa%20Kanken%20Taisaku%20Da%20yo%21%20%28Japan%29%20%28Rev%202%29.png

linking
DS Kageyama Method Dennou Hanpuku - Tadashii Kanji Kakitori-kun - Kondo wa Kanken Taisaku Da yo! (Japan).png to
DS Kageyama Method Dennou Hanpuku - Tadashii Kanji Kakitori-kun - Kondo wa Kanken Taisaku Da yo! (Japan) (Rev 1).png and
DS Kageyama Method Dennou Hanpuku - Tadashii Kanji Kakitori-kun - Kondo wa Kanken Taisaku Da yo! (Japan) (Rev 2).png

messed up and created the issue in the parent repo first... ( https://github.com/libretro-thumbnails/libretro-thumbnails/issues/133 )

**Comment by gerad-not-edgar** [comment]
Added this one to my PR #226.
